// Generated by GitHub Copilot
import { useState } from "react";

function TraceCard({ event }) {
    const [open, setOpen] = useState(false);

    return (
        <article
            style={{
                border: "1px solid #d8e2dc",
                borderRadius: 10,
                padding: 14,
                marginBottom: 12,
                background: "#fbfffb",
            }}
        >
            <button
                type="button"
                onClick={() => setOpen((prev) => !prev)}
                style={{
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    fontWeight: 700,
                    display: "flex",
                    justifyContent: "space-between",
                    width: "100%",
                    padding: 0,
                    textAlign: "left",
                }}
                aria-expanded={open}
            >
                <span>
                    {event.agent} - {event.stage}
                </span>
                <span>{open ? "Hide" : "Show"}</span>
            </button>
            <p style={{ marginTop: 8, marginBottom: 8 }}>{event.message}</p>
            <p style={{ margin: 0, fontSize: 12, color: "#475569" }}>
                {event.timestamp} | {Number(event.elapsed_ms || 0).toFixed(1)} ms
            </p>
            {open && (
                <pre
                    style={{
                        marginTop: 10,
                        whiteSpace: "pre-wrap",
                        fontSize: 12,
                        background: "#f8fafc",
                        borderRadius: 6,
                        padding: 10,
                        overflowX: "auto",
                    }}
                >
                    {JSON.stringify(event.payload, null, 2)}
                </pre>
            )}
        </article>
    );
}

export default TraceCard;
