// Generated by GitHub Copilot
import { useEffect, useMemo, useRef, useState } from "react";
import TraceCard from "./components/TraceCard";

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://127.0.0.1:8002";

function App() {
  const streamRef = useRef(null);
  const [query, setQuery] = useState("");
  const [maxSources, setMaxSources] = useState(5);
  const [events, setEvents] = useState([]);
  const [answer, setAnswer] = useState(null);
  const [status, setStatus] = useState("Idle");
  const [errorMessage, setErrorMessage] = useState("");
  const [metadata, setMetadata] = useState(null);
  const [running, setRunning] = useState(false);

  const canRun = useMemo(() => query.trim().length >= 3 && !running, [query, running]);

  /**
   * Close active EventSource stream and clear reference.
   */
  function stopStream() {
    if (streamRef.current) {
      streamRef.current.close();
      streamRef.current = null;
    }
    setRunning(false);
  }

  /**
   * Open SSE stream for research workflow and append incoming trace/answer events.
   */
  function runResearch() {
    if (!canRun) {
      return;
    }

    setEvents([]);
    setAnswer(null);
    setMetadata(null);
    setErrorMessage("");
    setStatus("Starting research workflow");

    const url = `${API_BASE_URL}/research?query=${encodeURIComponent(query.trim())}&max_sources=${maxSources}`;
    const source = new EventSource(url);
    streamRef.current = source;
    setRunning(true);

    source.addEventListener("metadata", (event) => {
      setMetadata(JSON.parse(event.data));
      setStatus("Retrieving evidence");
    });

    source.addEventListener("trace", (event) => {
      const payload = JSON.parse(event.data);
      setEvents((prev) => [...prev, payload]);
      setStatus(`Running ${payload.agent} agent`);
    });

    source.addEventListener("answer", (event) => {
      setAnswer(JSON.parse(event.data));
      setStatus("Research complete");
      stopStream();
    });

    source.addEventListener("error", (event) => {
      try {
        const payload = JSON.parse(event.data);
        setErrorMessage(payload.detail || "Research workflow failed");
      } catch {
        setErrorMessage("Research workflow failed");
      }
      setStatus("Error");
      stopStream();
    });

    source.onerror = () => {
      setErrorMessage((previous) => previous || "SSE connection interrupted");
      setStatus("Connection closed");
      stopStream();
    };
  }

  useEffect(() => () => stopStream(), []);

  return (
    <main
      style={{
        maxWidth: 1080,
        margin: "24px auto",
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        padding: 16,
        color: "#102a43",
      }}
    >
      <h1 style={{ marginBottom: 8 }}>Agentic Research Assistant</h1>
      <p style={{ marginTop: 0, color: "#334e68" }}>
        Multi-agent research with Searcher, Summarizer, and Critic traces streamed in real time.
      </p>

      <section
        aria-label="Research controls"
        style={{
          border: "1px solid #bcccdc",
          borderRadius: 12,
          padding: 16,
          background: "linear-gradient(180deg, #f8fcff 0%, #eef6ff 100%)",
        }}
      >
        <label htmlFor="query-input" style={{ fontWeight: 600 }}>
          Research Query
        </label>
        <textarea
          id="query-input"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Example: Compare modern secrets management patterns for enterprise microservices"
          rows={4}
          style={{ width: "100%", marginTop: 8, padding: 10, borderRadius: 8, border: "1px solid #9fb3c8" }}
        />

        <div style={{ display: "flex", gap: 12, alignItems: "center", marginTop: 12, flexWrap: "wrap" }}>
          <label htmlFor="max-sources" style={{ fontWeight: 600 }}>
            Max Sources
          </label>
          <select
            id="max-sources"
            value={maxSources}
            onChange={(event) => setMaxSources(Number(event.target.value))}
            disabled={running}
            style={{ padding: "8px 10px", borderRadius: 8, border: "1px solid #9fb3c8" }}
          >
            {[3, 4, 5, 6, 7, 8].map((value) => (
              <option key={value} value={value}>
                {value}
              </option>
            ))}
          </select>

          <button
            type="button"
            onClick={runResearch}
            disabled={!canRun}
            style={{ padding: "10px 14px", borderRadius: 8, border: "1px solid #486581", background: "#486581", color: "white" }}
          >
            Start Research
          </button>
          <button
            type="button"
            onClick={stopStream}
            disabled={!running}
            style={{ padding: "10px 14px", borderRadius: 8, border: "1px solid #9fb3c8", background: "#f0f4f8" }}
          >
            Stop Stream
          </button>
        </div>

        <p aria-live="polite" style={{ marginTop: 12, marginBottom: 0 }}>
          <strong>Status:</strong> {status}
        </p>
        {metadata && (
          <p style={{ marginTop: 8, marginBottom: 0, fontSize: 13, color: "#486581" }}>
            Request: {metadata.request_id} | Started: {metadata.started_at}
          </p>
        )}
        {errorMessage && (
          <p role="alert" style={{ marginTop: 8, marginBottom: 0, color: "#9b1c1c", fontWeight: 600 }}>
            {errorMessage}
          </p>
        )}
      </section>

      <section aria-label="Trace stream" style={{ marginTop: 18 }}>
        <h2 style={{ marginBottom: 10 }}>Execution Trace ({events.length})</h2>
        {events.length === 0 && <p style={{ color: "#627d98" }}>No trace events yet.</p>}
        {events.map((event, index) => (
          <TraceCard key={`${event.agent}-${event.timestamp}-${index}`} event={event} />
        ))}
      </section>

      {answer && (
        <section
          style={{
            marginTop: 20,
            border: "1px solid #d9e2ec",
            borderRadius: 12,
            padding: 16,
            background: "#ffffff",
          }}
          aria-label="Final answer"
        >
          <h2 style={{ marginTop: 0 }}>Final Answer</h2>
          <p>
            <strong>Duration:</strong> {Number(answer.duration_ms).toFixed(1)} ms | <strong>Traces:</strong>{" "}
            {answer.trace_count}
          </p>

          <h3>Summary</h3>
          <pre style={{ whiteSpace: "pre-wrap", background: "#f8fafc", padding: 12, borderRadius: 8 }}>
            {answer.summary}
          </pre>

          <h3>Critic Verdict</h3>
          <p>
            <strong>{String(answer.critique?.verdict || "unknown")}</strong> with confidence {answer.critique?.confidence}
          </p>
          {Array.isArray(answer.critique?.gaps) && answer.critique.gaps.length > 0 && (
            <ul>
              {answer.critique.gaps.map((gap) => (
                <li key={gap}>{gap}</li>
              ))}
            </ul>
          )}

          <h3>Sources</h3>
          <ul>
            {(answer.sources || []).map((source) => (
              <li key={`${source.title}-${source.url}`}>
                <a href={source.url} target="_blank" rel="noreferrer">
                  {source.title}
                </a>
              </li>
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}

export default App;
