# Generated by GitHub Copilot
"""Run production smoke checks for API health, metrics auth, and SSE flow."""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import dataclass
from typing import Any, Iterator

import requests
from requests import Response


class SmokeCheckError(RuntimeError):
    """Raised when one of the smoke checks fails."""


@dataclass(frozen=True)
class SmokeConfig:
    """Holds runtime configuration for smoke-test execution."""

    api_base_url: str
    frontend_url: str
    workflow_api_key: str
    metrics_key: str
    query: str
    max_sources: int
    timeout_seconds: int
    verify_tls: bool
    skip_frontend_check: bool


# Generated by GitHub Copilot
def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for smoke-test execution."""

    parser = argparse.ArgumentParser(description="Run production smoke checks against deployed services.")
    parser.add_argument("--api-base-url", default="http://127.0.0.1:8002", help="Base URL for API service")
    parser.add_argument("--frontend-url", default="http://127.0.0.1:4175", help="Frontend URL")
    parser.add_argument("--workflow-api-key", default="", help="Optional X-API-Key for research endpoints")
    parser.add_argument("--metrics-key", default="", help="Optional X-Metrics-Key for /metrics endpoint")
    parser.add_argument(
        "--query",
        default="Compare modern API gateway patterns",
        help="Research query used for the SSE smoke check",
    )
    parser.add_argument("--max-sources", type=int, default=4, help="max_sources query parameter for SSE test")
    parser.add_argument("--timeout-seconds", type=int, default=60, help="Timeout per check in seconds")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS verification")
    parser.add_argument("--skip-frontend-check", action="store_true", help="Skip frontend availability check")
    return parser.parse_args()


# Generated by GitHub Copilot
def build_config(args: argparse.Namespace) -> SmokeConfig:
    """Build validated smoke-test configuration from parsed arguments."""

    query = " ".join(args.query.split()).strip()
    if len(query) < 3:
        raise SmokeCheckError("query must contain at least 3 characters")
    if args.max_sources < 1 or args.max_sources > 8:
        raise SmokeCheckError("max_sources must be between 1 and 8")
    if args.timeout_seconds < 5:
        raise SmokeCheckError("timeout_seconds must be >= 5")

    return SmokeConfig(
        api_base_url=args.api_base_url.rstrip("/"),
        frontend_url=args.frontend_url.rstrip("/"),
        workflow_api_key=args.workflow_api_key,
        metrics_key=args.metrics_key,
        query=query,
        max_sources=args.max_sources,
        timeout_seconds=args.timeout_seconds,
        verify_tls=not args.insecure,
        skip_frontend_check=bool(args.skip_frontend_check),
    )


# Generated by GitHub Copilot
def print_pass(message: str) -> None:
    """Print a successful smoke-check step outcome."""

    print(f"[PASS] {message}")


# Generated by GitHub Copilot
def print_fail(message: str) -> None:
    """Print a failed smoke-check step outcome."""

    print(f"[FAIL] {message}")


# Generated by GitHub Copilot
def request(
    method: str,
    url: str,
    timeout_seconds: int,
    verify_tls: bool,
    headers: dict[str, str] | None = None,
    params: dict[str, Any] | None = None,
) -> Response:
    """Execute one HTTP request with normalized timeout and TLS settings."""

    response = requests.request(
        method=method,
        url=url,
        headers=headers,
        params=params,
        timeout=(5, timeout_seconds),
        verify=verify_tls,
    )
    return response


# Generated by GitHub Copilot
def check_frontend(config: SmokeConfig) -> None:
    """Validate that the frontend service is reachable and returns HTTP 200."""

    if config.skip_frontend_check:
        print_pass("frontend check skipped")
        return

    response = request("GET", config.frontend_url, config.timeout_seconds, config.verify_tls)
    if response.status_code != 200:
        raise SmokeCheckError(f"frontend returned unexpected status {response.status_code}")
    print_pass("frontend endpoint is reachable")


# Generated by GitHub Copilot
def check_health(config: SmokeConfig) -> None:
    """Validate API health endpoint and key fields in the response payload."""

    url = f"{config.api_base_url}/health"
    response = request("GET", url, config.timeout_seconds, config.verify_tls)
    if response.status_code != 200:
        raise SmokeCheckError(f"/health returned unexpected status {response.status_code}")

    payload = response.json()
    if payload.get("status") != "ok":
        raise SmokeCheckError("/health status was not 'ok'")
    if int(payload.get("rate_limit_per_minute", 0)) <= 0:
        raise SmokeCheckError("/health reported invalid rate_limit_per_minute")

    print_pass("/health endpoint is healthy")


# Generated by GitHub Copilot
def check_metrics(config: SmokeConfig) -> None:
    """Validate metrics endpoint behavior with and without metrics key."""

    url = f"{config.api_base_url}/metrics"

    if config.metrics_key:
        unauthorized = request("GET", url, config.timeout_seconds, config.verify_tls)
        if unauthorized.status_code != 401:
            raise SmokeCheckError(
                f"expected /metrics to return 401 without key, got {unauthorized.status_code}"
            )

        authorized = request(
            "GET",
            url,
            config.timeout_seconds,
            config.verify_tls,
            headers={"X-Metrics-Key": config.metrics_key},
        )
        if authorized.status_code != 200:
            raise SmokeCheckError(f"/metrics with key returned {authorized.status_code}")
        body = authorized.text
    else:
        public_metrics = request("GET", url, config.timeout_seconds, config.verify_tls)
        if public_metrics.status_code != 200:
            raise SmokeCheckError(f"/metrics returned {public_metrics.status_code}")
        body = public_metrics.text

    if "research_api_requests_total" not in body:
        raise SmokeCheckError("/metrics response did not include research_api_requests_total")

    print_pass("/metrics endpoint check passed")


# Generated by GitHub Copilot
def iter_sse_events(response: Response, max_duration_seconds: int) -> Iterator[tuple[str, str]]:
    """Yield parsed Server-Sent Events from a streaming HTTP response."""

    started = time.monotonic()
    current_event = "message"
    data_lines: list[str] = []

    for raw_line in response.iter_lines(decode_unicode=True):
        if time.monotonic() - started > max_duration_seconds:
            raise SmokeCheckError("timed out while waiting for SSE events")

        if raw_line is None:
            continue

        line = raw_line.rstrip("\r")

        if line == "":
            if data_lines:
                yield current_event, "\n".join(data_lines)
            current_event = "message"
            data_lines = []
            continue

        if line.startswith(":"):
            continue

        if line.startswith("event:"):
            current_event = line[len("event:") :].strip() or "message"
            continue

        if line.startswith("data:"):
            data_lines.append(line[len("data:") :].lstrip())

    if data_lines:
        yield current_event, "\n".join(data_lines)


# Generated by GitHub Copilot
def check_sse_research(config: SmokeConfig) -> None:
    """Validate that SSE research stream emits metadata, trace, and final answer events."""

    url = f"{config.api_base_url}/research"
    headers: dict[str, str] = {"Accept": "text/event-stream"}
    if config.workflow_api_key:
        headers["X-API-Key"] = config.workflow_api_key

    params = {"query": config.query, "max_sources": config.max_sources}

    response = requests.get(
        url,
        params=params,
        headers=headers,
        timeout=(5, config.timeout_seconds),
        verify=config.verify_tls,
        stream=True,
    )

    if response.status_code != 200:
        raise SmokeCheckError(
            f"/research returned unexpected status {response.status_code}; provide --workflow-api-key if required"
        )

    metadata_seen = False
    trace_events = 0
    answer_payload: dict[str, Any] | None = None

    try:
        for event_name, payload in iter_sse_events(response, config.timeout_seconds):
            if event_name == "metadata":
                metadata_seen = True
                continue

            if event_name == "trace":
                trace_events += 1
                continue

            if event_name == "error":
                try:
                    error_payload = json.loads(payload)
                except json.JSONDecodeError as exc:
                    raise SmokeCheckError(f"SSE error payload was not valid JSON: {payload}") from exc
                raise SmokeCheckError(f"SSE error event: {error_payload}")

            if event_name == "answer":
                try:
                    answer_payload = json.loads(payload)
                except json.JSONDecodeError as exc:
                    raise SmokeCheckError("SSE answer payload was not valid JSON") from exc
                break
    finally:
        response.close()

    if not metadata_seen:
        raise SmokeCheckError("SSE stream did not emit metadata event")
    if trace_events == 0:
        raise SmokeCheckError("SSE stream did not emit trace events")
    if not answer_payload:
        raise SmokeCheckError("SSE stream did not emit final answer event")
    if not str(answer_payload.get("summary", "")).strip():
        raise SmokeCheckError("SSE answer summary was empty")

    print_pass("/research SSE emitted metadata, trace, and answer events")


# Generated by GitHub Copilot
def run_smoke_test(config: SmokeConfig) -> None:
    """Run all smoke checks in a stable order for deployment validation."""

    print("Running production smoke test...")
    print(f"API base URL: {config.api_base_url}")

    check_frontend(config)
    check_health(config)
    check_metrics(config)
    check_sse_research(config)


# Generated by GitHub Copilot
def main() -> int:
    """Program entrypoint that returns process exit code for CI and scripts."""

    try:
        args = parse_args()
        config = build_config(args)
        run_smoke_test(config)
    except SmokeCheckError as exc:
        print_fail(str(exc))
        return 1
    except requests.RequestException as exc:
        print_fail(f"HTTP request failed: {exc}")
        return 1
    except Exception as exc:  # pragma: no cover
        print_fail(f"Unexpected error: {exc}")
        return 1

    print_pass("all smoke checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
