# Generated by GitHub Copilot
[CmdletBinding()]
param(
    [string]$ApiBaseUrl = "http://127.0.0.1:8002",
    [string]$FrontendUrl = "http://127.0.0.1:4175",
    [string]$WorkflowApiKey = "",
    [string]$MetricsKey = "",
    [string]$Query = "Compare modern API gateway patterns",
    [int]$MaxSources = 4,
    [int]$TimeoutSeconds = 60,
    [switch]$SkipFrontendCheck,
    [switch]$Insecure
)

$ErrorActionPreference = "Stop"

$scriptPath = Join-Path $PSScriptRoot "production_smoke_test.py"
if (-not (Test-Path $scriptPath)) {
    Write-Error "Could not find smoke test script at $scriptPath"
    exit 1
}

$pythonCmd = ""
if (Get-Command python -ErrorAction SilentlyContinue) {
    $pythonCmd = "python"
} elseif (Get-Command py -ErrorAction SilentlyContinue) {
    $pythonCmd = "py"
} else {
    Write-Error "Python executable not found in PATH"
    exit 1
}

$arguments = @(
    $scriptPath,
    "--api-base-url", $ApiBaseUrl,
    "--frontend-url", $FrontendUrl,
    "--query", $Query,
    "--max-sources", "$MaxSources",
    "--timeout-seconds", "$TimeoutSeconds"
)

if ($WorkflowApiKey) {
    $arguments += @("--workflow-api-key", $WorkflowApiKey)
}
if ($MetricsKey) {
    $arguments += @("--metrics-key", $MetricsKey)
}
if ($SkipFrontendCheck.IsPresent) {
    $arguments += "--skip-frontend-check"
}
if ($Insecure.IsPresent) {
    $arguments += "--insecure"
}

& $pythonCmd @arguments
exit $LASTEXITCODE
